### ISSUE TITLE
requirements.txt needs updating

### ISSUE THREAD

**Issue by hinkelman** [leogoesger/func-flow#110]
I'm a Python beginner, but struggled to install all of the dependencies in `requirements.txt`. I resorted to stripping all of the version numbers in `requirements.txt` and then adding version constraints as directed by `pip`. I'm guessing that is not the best approach, but I was able to successfully run `python3 main.py` after taking that approach. By successful, I mean that it ran without errors based on my arbitrary selections at the prompts, but I haven't looked at any outputs yet.

**Comment by hinkelman** [comment]
I will add a few more details. I ran `main.py` on Windows 10 and macOS High Sierra. For both operating systems, `pip` guided me to the same version constraints: `gast` (0.3.3), `lazy-object-proxy` (1.4.3), `numpy` (1.18.5), and `scipy` (1.4.1). On Windows 10, I also needed to constrain `ecos` (2.0.7.post1).

**Comment by kklausmeyer** [comment]
I am also having trouble installing the dependencies on a windows machine with python virtual environment.  I installed python 3.6.4 to try to replicate the instructions, but I get the following error:

Collecting cvxpy==1.0.14 (from -r requirements.txt (line 6))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/dc/bb/4f7e6f9d4e4312283bdceb3f2d2f12e348e0001745261da296a8eaf2ca92/cvxpy-1.0.14.tar.gz (913kB)
    100% |████████████████████████████████| 921kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\KKLAUS~1.TNC\AppData\Local\Temp\easy_install-su05lpct\numpy-1.20.1\setup.py", line 30, in <module>

    RuntimeError: Python version >= 3.7 required.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\KKLAUS~1.TNC\AppData\Local\Temp\pip-build-j_fxse2j\cvxpy\setup.py", line 77, in <module>
        use_2to3=True,
      File "C:\Users\kklausmeyer.TNC\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "C:\Users\kklausmeyer.TNC\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\kklausmeyer.TNC\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\users\kklausmeyer.tnc\documents\workspace\func-flow\func-flow\my-virtualenv\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\KKLAUS~1.TNC\AppData\Local\Temp\easy_install-su05lpct\numpy-1.20.1\setup.py", line 30, in <module>

    RuntimeError: Python version >= 3.7 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\KKLAUS~1.TNC\AppData\Local\Temp\pip-build-j_fxse2j\cvxpy\
You are using pip version 9.0.1, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by bobo-baggins** [comment]
I've updated the requiments.txt file on a fork, but to get this code working you need to replace depcreated function call 'np.float' with 'float' to work with latest numpy packaged. 

Requirement.txt updated
absl-py==2.0.0
astunparse==1.6.3
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.2
clarabel==0.6.0
contourpy==1.2.0
cvxpy==1.4.1
cycler==0.12.1
dill==0.3.7
ecos==2.0.12
flatbuffers==23.5.26
fonttools==4.44.0
gast==0.5.4
google-auth==2.23.4
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.59.2
h5py==3.10.0
idna==3.4
keras==2.14.0
kiwisolver==1.4.5
libclang==16.0.6
Markdown==3.5.1
MarkupSafe==2.1.3
matplotlib==3.8.1
ml-dtypes==0.2.0
multiprocess==0.70.15
numpy==1.26.2
oauthlib==3.2.2
opt-einsum==3.3.0
osqp==0.6.3
packaging==23.2
pandas==2.1.3
Pillow==10.1.0
protobuf==4.25.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybind11==2.11.1
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
qdldl==0.1.7.post0
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scipy==1.11.3
scs==3.2.4
six==1.16.0
tensorboard==2.14.1
tensorboard-data-server==0.7.2
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.1.0
Werkzeug==3.0.1
wrapt==1.14.1
